// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.cil.grpc;

public interface SendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.SendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgSrc = 1;</code>
   */
  String getMsgSrc();
  /**
   * <code>string msgSrc = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgSrcBytes();

  /**
   * <code>string inscd = 2;</code>
   */
  String getInscd();
  /**
   * <code>string inscd = 2;</code>
   */
  com.google.protobuf.ByteString
      getInscdBytes();

  /**
   * <code>string groupCode = 3;</code>
   */
  String getGroupCode();
  /**
   * <code>string groupCode = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupCodeBytes();

  /**
   * <code>string msgType = 4;</code>
   */
  String getMsgType();
  /**
   * <code>string msgType = 4;</code>
   */
  com.google.protobuf.ByteString
      getMsgTypeBytes();

  /**
   * <code>string orderAmt = 5;</code>
   */
  String getOrderAmt();
  /**
   * <code>string orderAmt = 5;</code>
   */
  com.google.protobuf.ByteString
      getOrderAmtBytes();

  /**
   * <code>string discountAmt = 6;</code>
   */
  String getDiscountAmt();
  /**
   * <code>string discountAmt = 6;</code>
   */
  com.google.protobuf.ByteString
      getDiscountAmtBytes();

  /**
   * <code>string merCode = 7;</code>
   */
  String getMerCode();
  /**
   * <code>string merCode = 7;</code>
   */
  com.google.protobuf.ByteString
      getMerCodeBytes();

  /**
   * <code>string merName = 8;</code>
   */
  String getMerName();
  /**
   * <code>string merName = 8;</code>
   */
  com.google.protobuf.ByteString
      getMerNameBytes();

  /**
   * <code>string cardBrand = 9;</code>
   */
  String getCardBrand();
  /**
   * <code>string cardBrand = 9;</code>
   */
  com.google.protobuf.ByteString
      getCardBrandBytes();

  /**
   * <code>string txnType = 10;</code>
   */
  String getTxnType();
  /**
   * <code>string txnType = 10;</code>
   */
  com.google.protobuf.ByteString
      getTxnTypeBytes();

  /**
   * <code>string orderNum = 11;</code>
   */
  String getOrderNum();
  /**
   * <code>string orderNum = 11;</code>
   */
  com.google.protobuf.ByteString
      getOrderNumBytes();

  /**
   * <code>string transTime = 12;</code>
   */
  String getTransTime();
  /**
   * <code>string transTime = 12;</code>
   */
  com.google.protobuf.ByteString
      getTransTimeBytes();

  /**
   * <code>string transCurr = 13;</code>
   */
  String getTransCurr();
  /**
   * <code>string transCurr = 13;</code>
   */
  com.google.protobuf.ByteString
      getTransCurrBytes();

  /**
   * <code>string subOpenid = 14;</code>
   */
  String getSubOpenid();
  /**
   * <code>string subOpenid = 14;</code>
   */
  com.google.protobuf.ByteString
      getSubOpenidBytes();

  /**
   * <code>string subAppid = 15;</code>
   */
  String getSubAppid();
  /**
   * <code>string subAppid = 15;</code>
   */
  com.google.protobuf.ByteString
      getSubAppidBytes();

  /**
   * <code>string settFlag = 16;</code>
   */
  String getSettFlag();
  /**
   * <code>string settFlag = 16;</code>
   */
  com.google.protobuf.ByteString
      getSettFlagBytes();

  /**
   * <code>string checkCode = 17;</code>
   */
  String getCheckCode();
  /**
   * <code>string checkCode = 17;</code>
   */
  com.google.protobuf.ByteString
      getCheckCodeBytes();

  /**
   * <code>string origTxnType = 18;</code>
   */
  String getOrigTxnType();
  /**
   * <code>string origTxnType = 18;</code>
   */
  com.google.protobuf.ByteString
      getOrigTxnTypeBytes();

  /**
   * <code>string termCode = 19;</code>
   */
  String getTermCode();
  /**
   * <code>string termCode = 19;</code>
   */
  com.google.protobuf.ByteString
      getTermCodeBytes();

  /**
   * <code>string chanOrderNum = 20;</code>
   */
  String getChanOrderNum();
  /**
   * <code>string chanOrderNum = 20;</code>
   */
  com.google.protobuf.ByteString
      getChanOrderNumBytes();

  /**
   * <code>string origOrderNum = 21;</code>
   */
  String getOrigOrderNum();
  /**
   * <code>string origOrderNum = 21;</code>
   */
  com.google.protobuf.ByteString
      getOrigOrderNumBytes();

  /**
   * <code>string attach = 22;</code>
   */
  String getAttach();
  /**
   * <code>string attach = 22;</code>
   */
  com.google.protobuf.ByteString
      getAttachBytes();

  /**
   * <code>string merDiscount = 23;</code>
   */
  String getMerDiscount();
  /**
   * <code>string merDiscount = 23;</code>
   */
  com.google.protobuf.ByteString
      getMerDiscountBytes();

  /**
   * <code>string chcdDiscount = 24;</code>
   */
  String getChcdDiscount();
  /**
   * <code>string chcdDiscount = 24;</code>
   */
  com.google.protobuf.ByteString
      getChcdDiscountBytes();

  /**
   * <code>string outOrderNum = 25;</code>
   */
  String getOutOrderNum();
  /**
   * <code>string outOrderNum = 25;</code>
   */
  com.google.protobuf.ByteString
      getOutOrderNumBytes();

  /**
   * <code>string respcd = 26;</code>
   */
  String getRespcd();
  /**
   * <code>string respcd = 26;</code>
   */
  com.google.protobuf.ByteString
      getRespcdBytes();

  /**
   * <code>string recvInsName = 27;</code>
   */
  String getRecvInsName();
  /**
   * <code>string recvInsName = 27;</code>
   */
  com.google.protobuf.ByteString
      getRecvInsNameBytes();

  /**
   * <code>string retrivlRefNum = 28;</code>
   */
  String getRetrivlRefNum();
  /**
   * <code>string retrivlRefNum = 28;</code>
   */
  com.google.protobuf.ByteString
      getRetrivlRefNumBytes();

  /**
   * <code>string origretrivlRefNum = 29;</code>
   */
  String getOrigretrivlRefNum();
  /**
   * <code>string origretrivlRefNum = 29;</code>
   */
  com.google.protobuf.ByteString
      getOrigretrivlRefNumBytes();

  /**
   * <code>string terminalid = 30;</code>
   */
  String getTerminalid();
  /**
   * <code>string terminalid = 30;</code>
   */
  com.google.protobuf.ByteString
      getTerminalidBytes();

  /**
   * <code>string respAuthCode = 31;</code>
   */
  String getRespAuthCode();
  /**
   * <code>string respAuthCode = 31;</code>
   */
  com.google.protobuf.ByteString
      getRespAuthCodeBytes();

  /**
   * <code>string consumerAccount = 32;</code>
   */
  String getConsumerAccount();
  /**
   * <code>string consumerAccount = 32;</code>
   */
  com.google.protobuf.ByteString
      getConsumerAccountBytes();

  /**
   * <code>string userDef = 33;</code>
   */
  String getUserDef();
  /**
   * <code>string userDef = 33;</code>
   */
  com.google.protobuf.ByteString
      getUserDefBytes();
}
