// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.cil.grpc;

public interface SendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.SendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
