// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.cil.grpc;

public final class SendProto {
  private SendProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\npush.proto\022\002pb\"\215\005\n\013SendRequest\022\016\n\006msgS" +
      "rc\030\001 \001(\t\022\r\n\005inscd\030\002 \001(\t\022\021\n\tgroupCode\030\003 \001" +
      "(\t\022\017\n\007msgType\030\004 \001(\t\022\020\n\010orderAmt\030\005 \001(\t\022\023\n" +
      "\013discountAmt\030\006 \001(\t\022\017\n\007merCode\030\007 \001(\t\022\017\n\007m" +
      "erName\030\010 \001(\t\022\021\n\tcardBrand\030\t \001(\t\022\017\n\007txnTy" +
      "pe\030\n \001(\t\022\020\n\010orderNum\030\013 \001(\t\022\021\n\ttransTime\030" +
      "\014 \001(\t\022\021\n\ttransCurr\030\r \001(\t\022\021\n\tsubOpenid\030\016 " +
      "\001(\t\022\020\n\010subAppid\030\017 \001(\t\022\020\n\010settFlag\030\020 \001(\t\022" +
      "\021\n\tcheckCode\030\021 \001(\t\022\023\n\013origTxnType\030\022 \001(\t\022" +
      "\020\n\010termCode\030\023 \001(\t\022\024\n\014chanOrderNum\030\024 \001(\t\022",
      "\024\n\014origOrderNum\030\025 \001(\t\022\016\n\006attach\030\026 \001(\t\022\023\n" +
      "\013merDiscount\030\027 \001(\t\022\024\n\014chcdDiscount\030\030 \001(\t" +
      "\022\023\n\013outOrderNum\030\031 \001(\t\022\016\n\006respcd\030\032 \001(\t\022\023\n" +
      "\013recvInsName\030\033 \001(\t\022\025\n\rretrivlRefNum\030\034 \001(" +
      "\t\022\031\n\021origretrivlRefNum\030\035 \001(\t\022\022\n\nterminal" +
      "id\030\036 \001(\t\022\024\n\014respAuthCode\030\037 \001(\t\022\027\n\017consum" +
      "erAccount\030  \001(\t\022\017\n\007userDef\030! \001(\t\"\037\n\014Send" +
      "Response\022\017\n\007message\030\001 \001(\t2:\n\013SendService" +
      "\022+\n\004Send\022\017.pb.SendRequest\032\020.pb.SendRespo" +
      "nse\"\000B\034\n\rcom.cil.protoB\tSendProtoP\001b\006pro",
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SendRequest_descriptor,
        new String[] { "MsgSrc", "Inscd", "GroupCode", "MsgType", "OrderAmt", "DiscountAmt", "MerCode", "MerName", "CardBrand", "TxnType", "OrderNum", "TransTime", "TransCurr", "SubOpenid", "SubAppid", "SettFlag", "CheckCode", "OrigTxnType", "TermCode", "ChanOrderNum", "OrigOrderNum", "Attach", "MerDiscount", "ChcdDiscount", "OutOrderNum", "Respcd", "RecvInsName", "RetrivlRefNum", "OrigretrivlRefNum", "Terminalid", "RespAuthCode", "ConsumerAccount", "UserDef", });
    internal_static_pb_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SendResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
